-- Track every AppSumo license_key we hear about, plus its redemption state.
-- Run this in your Supabase SQL Editor.
--
-- One row per license_key. The license_key itself is the natural unique
-- identifier (UUID generated by AppSumo). We never generate these — they
-- come from AppSumo's purchase/activate webhooks and from the OAuth flow.
--
-- Lifecycle:
--   1. `purchase` webhook arrives  →  row inserted with status='purchased',
--      organization_id NULL (no user has redeemed it yet).
--   2. User completes OAuth on /appsumo/redeem  →  organization_id and
--      redeemed_by_user_id get set, status flips to 'activated'.
--   3. `activate` webhook may arrive separately  →  status stays 'activated'
--      (idempotent).
--   4. `deactivate` webhook (refund / staff revoke)  →  status='deactivated',
--      deactivated_at set, organization downgraded back to free.
--   5. `upgrade` / `downgrade`  →  AppSumo generates a NEW license_key. We
--      insert the new key linked to the same organization (via
--      prev_license_key) and mark the old key deactivated.
--
-- One-time use is enforced at the row level: once organization_id is set,
-- the redemption API rejects any further attempts to claim the same key.

CREATE TABLE IF NOT EXISTS appsumo_codes (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- AppSumo identifiers
  license_key text NOT NULL UNIQUE,
  prev_license_key text,                       -- set on upgrade/downgrade rows
  parent_license_key text,                     -- set on add-on rows
  partner_plan_name text,                      -- set on add-on rows
  tier integer,
  unit_quantity integer,

  -- Redemption linkage (NULL until the customer completes OAuth on our side)
  organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
  redeemed_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,

  -- Lifecycle
  status text NOT NULL DEFAULT 'purchased'
    CHECK (status IN ('purchased', 'activated', 'deactivated', 'upgraded', 'downgraded')),
  activated_at timestamptz,
  deactivated_at timestamptz,

  -- Audit / support
  last_event text,                             -- last webhook event we saw
  last_payload jsonb,                          -- raw payload of the last event
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS appsumo_codes_organization_id_idx
  ON appsumo_codes (organization_id);

CREATE INDEX IF NOT EXISTS appsumo_codes_prev_license_key_idx
  ON appsumo_codes (prev_license_key)
  WHERE prev_license_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS appsumo_codes_parent_license_key_idx
  ON appsumo_codes (parent_license_key)
  WHERE parent_license_key IS NOT NULL;

-- Keep updated_at fresh on every UPDATE.
CREATE OR REPLACE FUNCTION appsumo_codes_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS appsumo_codes_set_updated_at_trigger ON appsumo_codes;
CREATE TRIGGER appsumo_codes_set_updated_at_trigger
  BEFORE UPDATE ON appsumo_codes
  FOR EACH ROW EXECUTE FUNCTION appsumo_codes_set_updated_at();

-- Enable RLS to match the rest of the schema. All AppSumo writes happen
-- via the service-role admin client, so we don't need any permissive
-- policies for end users.
ALTER TABLE appsumo_codes ENABLE ROW LEVEL SECURITY;
